# Generated by Django 4.2.1 on 2023-06-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('numbers', models.TextField()),
                ('is_words', models.TextField()),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fileapi.uploadedfile')),
            ],
        ),
    ]
